config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :tools do
    collection do
      get 'search'
      get 'autocomplete_tool_name'
    end
  end
  resources :reviews do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  root 'tools#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :review, counter_cache: :likes_count
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :tool
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :review, presence: true
  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_many :reviews
  accepts_nested_attributes_for :reviews

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    Comment.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(review_id: @review.id, user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, review_id: params[:review_id])
    @review = Review.find(params[:review_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, review_id: params[:review_id])
    like.destroy
    @review = Review.find(params[:review_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    @tool_id = review.tool.id
    review.update(update_params)
    redirect_to root_path
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to controller: :users, action: :index
  end

  private
  def update_params
    params.require(:review).permit(:review).merge(user_id: current_user.id, tool_id: @tool_id)
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  autocomplete :tool, :name, :full => true

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all
    @users = User.all
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
    @tool = Tool.find(params[:id])
    @reviews = @tool.reviews
  end

  # GET /tools/new
  def new
    @tool = Tool.new
    @tool.reviews.build
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.where(name: params[:tool][:name]).first_or_initialize
    if @tool.name.present? && params[:tool][:review][:review].present?
      @tool.save
      @review = Review.create(review_params)
      redirect_to tools_path and return
    else
      render 'new'
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @tools = Tool.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_params
      params.require(:tool).permit(:name)
    end

    def review_params
      params.require(:tool).require(:review).permit(:review).merge(user_id: current_user.id, tool_id: @tool.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @reviews = current_user.reviews
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tool_name(tool_id)
    Tool.find(tool_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div>
  <div>
    <h4>
      <%= comment.user.id %>
    </h4>
    <p>
      <%= comment.comment %>
    </p>
  </div>
</div>

app/views/comments/create.js.erb
$('#comments-number').text('コメント(<%= @review.comments.count %>)');
$('#comment_field').val('');
$('#comments').html('<%= j(render partial: 'comments/comment', collection: @review.comments) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IncSearch2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/likes/_like.html.erb
<% if review.like_user(current_user.id) %>
<!-- reviewに対してされているlikeをcurrent_userがつけている場合 -->
  <%= button_to review_like_path(review, like), method: :delete, id: "like-button", remote: true do %>
  <%= image_tag("red-heart.png") %>
  <span>
    <%= review.likes_count %>
  </span>
  <% end %>

<% else %>
<!-- reviewに対してされているlikeをcurrent_userがつけていない場合 -->
  <%= button_to review_likes_path(review), method: :post, id: "like-button", remote: true do %>
  <%= image_tag("gray-heart.png") %>
  <% if review.likes_count == nil %>
    <span>
      0
    </span>
  <% else %>
    <span>
      <%= review.likes_count %>
    </span>
  <% end %>
  <% end %>

<% end %>

app/views/likes/create.js.erb
$("#review-detail-like-button").html("<%= j(render partial: 'like', locals: { review: @review, like: @like }) %>");
$("#user-reviews-like-button" + <%= @review.id %>).html("<%= j(render partial: 'like', locals: { review: @review, like: @like }) %>");

app/views/likes/destroy.js.erb
$("#review-detail-like-button").html("<%= j(render partial: 'like', locals: { review: @review }) %>");
$("#user-reviews-like-button" + <%= @review.id %>).html("<%= j(render partial: 'like', locals: { review: @review }) %>");

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for @review do |f| %>
<div class="field">
  <%= f.label :review %>
  <%= f.text_field :review %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

<%= link_to 'Back', tools_path %>

app/views/reviews/show.html.erb
<!-- レビュー内容の表示 -->
<%= @review.review %>

<!-- 「いいね」ボタンの表示 -->
<div id="review-detail-like-button">
  <%= render partial: "likes/like", locals: { like: @review.likes.find_by(user_id: current_user.id), review: @review } %>
</div>

<!-- コメント総数の表示 -->
<div id="comments-number">
  コメント(<%= @review.comments.count %>)
</div>
<!-- コメントの表示 -->
<div id="comments">
  <%= render partial: 'comments/comment', collection: @review.comments %>
</div>
<div>
  <h4>コメントしてください</h4>
  <%= form_for [@review, @comment], remote: true do |f| %>
  <%= f.text_area :comment, id: "comment_field" %><br>
  <%= f.submit '送信' %>
  <% end %>
</div>

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <% if @tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tools/_tool.html.erb
<li>
  <%= tool.name %>
</li>

app/views/tools/edit.html.erb
<h1>Editing Tool</h1>

<%= render 'form' %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tools</h1>

<%= link_to '会員登録', new_user_registration_path %>
<%= link_to 'ログイン', user_session_path %>
<% if user_signed_in? %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to 'マイページ', users_path%>
<% end %>

<br>

<% if user_signed_in? %>
<p>ようこそ<%= current_user.id %>さん</p>
<% end %>

<%= link_to 'New Tool', new_tool_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tools.each do |tool| %>
    <tr>
      <td><%= tool.name %></td>
      <td><%= link_to 'Show', tool %></td>
      <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
      <td><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3>User</h3>

<% @users.each do |user| %>
<a href="/users/<%= user.id %>"><%= user.id %></a><br>
<% end %>

app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= form_for @tool do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.autocomplete_field :name, autocomplete_tool_name_tools_path, autofocus: true %>
</div>
<div class="field">
  <%= f.label :review %>
  <%= f.fields_for :review do |review_form| %>
  <%= review_form.text_field :review %>
  <% end %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

<%= link_to 'Back', tools_path %>

app/views/tools/search.js.erb
$("#tool_name").blur(function(){
  if($(this).val() == ""){
    $("#tool_list").html("");
  };
});

$("#tool_list").html("<%= j(render @tools) %>");

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tool.name %>
</p>

<% @tool.reviews.each do |review| %>
<a href="/users/<%= review.user.id %>"><%= review.user.id %></a>:<%= review.review %><br>
<% end %>

<br>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>

app/views/users/index.html.erb
<%= link_to 'Back', tools_path %>

<h3>投稿したアプリとレビュー</h3>

<% @reviews.each do |review| %>
<%= review.tool.name %><br>
<%= review.review %><%= link_to '編集', "/reviews/#{review.id}/edit" %><%= link_to '削除', "/reviews/#{review.id}", method: :delete %><br>
<% end %>

app/views/users/show.html.erb
<%= link_to 'Back', tools_path %>

<h3>投稿したアプリとレビュー</h3>

<% @reviews.each do |review| %>
<%= review.tool.name %><br>
<%= review.review %><%= link_to 'レビューの詳細', review_path(review) %><br>
<div id="user-reviews-like-button<%= review.id %>">
  <%= render partial: "likes/like", locals: { like: review.likes.find_by(user_id: current_user.id), review: review } %>
</div>
<% end %>